#+TITLE:   app/torrent
#+DATE:    October 6, 2020
#+SINCE:   v2.0.9
#+STARTUP: inlineimages nofold

* TODO Look into transmission-remote-cli-git and how it can provide a better interface

* Table of Contents :TOC_3:noexport:
- [[#description][Description]]
  - [[#module-flags][Module Flags]]
  - [[#plugins][Plugins]]
- [[#prerequisites][Prerequisites]]
- [[#features][Features]]

* Description
This module provides an interface to a transmission session.

** Module Flags
+ This module has no flags.

** Plugins
+ [[https://github.com/holomorph/transmission/][transmission.el]]

* Prerequisites
+ =transmission-cli= from your package manager.
+ Run =transmission-daemon= after installation to generate the configuration file. It should be located in '~/.config/transmission-daemon/settings.json'.
+ Before making any changes to the config file, run =transmission-remote --exit= otherwise changes will be overwritten.
+ Check for enable-daemon and port options, set the download location, save the changes and run =transmission-daemon= again.

* Features
One can add, start/stop, verify, remove torrents, set speed limits, ratio limits, bandwidth priorities, trackers, etc.  Also, one can navigate to the corresponding file list, torrent info, or peer info contexts.  In the file list, individual files can be toggled for download, and their priorities set.

|---------------------------+------------|
| Function                  | Keybinding |
|---------------------------+------------|
| transmission-add          | a          |
| transmission-info         | i          |
| transmission-stats        | s          |
| transmission-files        | RET        |
| transmission-toggle       | x          |
| transmission-remove       | D          |
| transmission-set-download | d          |
| transmission-set-upload   | u          |
| transmission-toggle-mark  | m          |
| transmission-unmark-all   | U          |
| transmission-quit         | q          |
|---------------------------+------------|
