#+title: Doom Emacs Configuration
#+author: Prashant Tak
#+email: prashantrameshtak@gmail.com
#+startup: fold

:DOC-CONFIG:
#+property: header-args:emacs-lisp :tangle config.el
:END:

The first edition of my soon-to-be literate configuration :P

1. NOTE: Run =org-babel-tangle= after making changes it to this file. Oddly enough, first time I had to run =doom sync=, need to look into this.
2. Look into =org-babel-demarcate-block= too.

* Todo
1. [X] Turn this into a literate Configuration
2. [ ] Improve the EXWM experience
3. [ ] Incorporate elvish and other configuration stuff within this.

* Config File Header
For the lexical binding of the elisp file.

#+BEGIN_SRC emacs-lisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; Here are some additional functions/macros that could help you configure Doom:
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c g k').
;; This will open documentation for it, including demos of how they are used.
;;
;; You can also try 'gd' (or 'C-c g d') to jump to their definition and see how
;; they are implemented.
#+END_SRC

* Hack to remove EXWM Warning
This is not functional since I moved from a ssignle EXWM file to a personal doom EXWM module but might be useful in the future if I decide to scrap that idea.

#+BEGIN_SRC emacs-lisp
;;(eshell-command "setq stringvar $XDG_CURRENT_DESKTOP")
;;(if (string= stringvar "EXWM")
;;   (load! "+exwm")
;;nil
;;)
#+END_SRC

* Customized Variables
To avoid the issue of reproducing your customize options.

#+BEGIN_SRC emacs-lisp
(setq-default
      user-full-name "Prashant Tak"
      user-mail-address "prashantrameshtak@gmail.com"
      doom-font (font-spec :family "Source Code Pro" :size 16)
      doom-variable-pitch-font (font-spec :family "iA Writer Quattro S")
      doom-serif-font (font-spec :family "iA Writer Quattro S" :weight 'regular)
      doom-theme 'doom-dracula
      org-directory "/mnt/Data/Documents/org/"
      evil-escape-mode 1
      display-line-numbers-type 'relative
      tab-width 8
      which-key-idle-delay 0.5
      large-file-warning-threshold nil
      org-latex-toc-command "\\tableofcontents \\clearpage"
      )

(display-time-mode 1)

(unless (equal "Battery status not available"
               (battery))
  (display-battery-mode 1))

#+END_SRC

Higlighting the new buffer when you open one should be the default, lrt's make it that way.

#+BEGIN_SRC emacs-lisp
(setq evil-split-window-below t
      evil-vsplit-window-right t)
#+END_SRC

Add some highlighting to woman pages

#+BEGIN_SRC emacs-lisp
(add-hook 'Info-selection-hook 'info-colors-fontify-node)
(add-hook 'Info-mode-hook #'mixed-pitch-mode)
#+END_SRC

Ensuring that emacs is focused after restarting

#+BEGIN_SRC emacs-lisp
(add-hook! 'window-setup-hook
  (select-frame-set-input-focus (selected-frame)))
#+END_SRC

Also =doom/window enlargen= has some freezing issues, this HACK attempts to fix them for the time being.

#+BEGIN_SRC emacs-lisp
(setq window-resize-pixelwise nil
      frame-resize-pixelwise nil)
#+END_SRC

Company's completion dialog frame takes a long time to show up, making it look slow, hence we reduce the idle delay.

#+BEGIN_SRC emacs-lisp
(after! company
  (setq company-idle-delay 0.2))
#+END_SRC

Also, I don't need the details dired provides all the time, so I disabled that.

#+BEGIN_SRC emacs-lisp
(add-hook 'dired-mode-hook 'dired-hide-details-mode)
#+END_SRC

Now this somehow makes notes of the changes you made using the customize wizard, but I need to look into its working yet.

#+BEGIN_SRC emacs-lisp
(setq-default custom-file (expand-file-name ".custom.el" doom-private-dir))
(when (file-exists-p custom-file)
  (load custom-file))
#+END_SRC

* LSP
I've yet to look more into the different speed-up and configuration options related to LSP but these are some basics that I yanked off the discord.

#+BEGIN_SRC
(after! lsp-ui (setq lsp-ui-doc-enable t))
(after! lsp-mode (setq lsp-enable-semantic-highlighting t))
#+END_SRC

* Org
Now I need to make all these changes coherent and consistent but for the time being I'm just dumping them here.

#+BEGIN_SRC emacs-lisp
(add-hook 'org-mode-hook 'org-fragtog-mode)
(add-hook 'org-mode-hook
          (λ! (yas-minor-mode)
              (yas-activate-extra-mode 'latex-mode)))
;; (add-hook 'org-mode-hook 'lsp-completion-mode)
#+END_SRC

Nested snippets are useful, let's enable them.

#+BEGIN_SRC emacs-lisp
(setq yas-triggers-in-field t)
#+END_SRC

Flycheck annoys whenever I have to export to pdf, let's disable it for tex files.

#+BEGIN_SRC emacs-lisp
(setq flycheck-global-modes '(not LaTeX-mode latex-mode))
#+END_SRC

For plotting graphs, one needs tikz and pfgplots. let's enable them by default, also preview of tikz graphs would be cool too.

#+BEGIN_SRC emacs-lisp
(setq org-preview-latex-default-process 'dvisvgm)
#+END_SRC
* Elfeed
I need to add shortcuts for update functions and reference to the org file, also need to fix the database update issue.

#+BEGIN_SRC emacs-lisp
(after! elfeed
  (setq elfeed-search-filter "@2-month-ago"))
(defun =elfeed ()
  (interactive)
  (elfeed)
  )
(map! :n "SPC o e" #'=elfeed)
#+END_SRC
* PDF-Mode
Need to fix the continuous scrolling package issue and add more shortcuts for general functions (maybe I should make a separate file for shortcuts, or learn about hydras :p)

#+BEGIN_SRC emacs-lisp
(add-hook 'pdf-view-mode-hook (lambda ()
        (pdf-view-midnight-minor-mode)))
(add-hook 'pdf-view-mode-hook 'pdf-view-auto-slice-minor-mode)
;;(setq pdf-view-midnight-colors '("#839496" . "#002b36" ))
#+END_SRC
* Dashboard
Most of the default functions have been stored in my memory, let's turn the dashboard into an /"emacs app drawer"/. (Also I need to find a better splash, there are also issues with splash and exwm which I'll look into *later*.)

#+BEGIN_SRC emacs-lisp
;; (setq fancy-splash-image "~/.doom.d/doom_grin.png")
(setq +doom-dashboard-menu-sections
  '(("Reload last session"
     :icon (all-the-icons-octicon "history" :face 'doom-dashboard-menu-title)
     :when (cond ((require 'persp-mode nil t)
                  (file-exists-p (expand-file-name persp-auto-save-fname persp-save-dir)))
                 ((require 'desktop nil t)
                  (file-exists-p (desktop-full-file-name))))
     :face (:inherit (doom-dashboard-menu-title bold))
     :action doom/quickload-session)
    ("Open notmuch"
     :icon (all-the-icons-octicon "mention" :face 'doom-dashboard-menu-title)
     :face (:inherit (doom-dashboard-menu-title bold))
     :action =notmuch)
    ("Open elfeed"
     :icon (all-the-icons-octicon "book" :face 'doom-dashboard-menu-title)
     :face (:inherit (doom-dashboard-menu-title bold))
     :action =elfeed)
    )
  )
#+END_SRC
* Windmove
Switching buffers using C-x o is a major pain, I like my arrow keys, so let's add those options.
#+BEGIN_SRC emacs-lisp
(use-package windmove
  :bind
  (("S-<left>". windmove-left)
   ("S-<right>". windmove-right)
   ("S-<up>". windmove-up)
   ("S-<down>". windmove-down)))

(add-hook 'org-shiftup-final-hook 'windmove-up)
(add-hook 'org-shiftleft-final-hook 'windmove-left)
(add-hook 'org-shiftdown-final-hook 'windmove-down)
(add-hook 'org-shiftright-final-hook 'windmove-right)
(setq org-support-shift-select 'always)
#+END_SRC

* Mail
# TODO Add the mbsync configuration and notmuch script
While notmuch is satisfying the reading mails part, I still have to figure out the other basic functionalities, sending, replying, deleting et al.

#+BEGIN_SRC emacs-lisp
(setq +notmuch-sync-backend 'mbsync)
(autoload 'notmuch "notmuch" "notmuch mail" t)
;; setup the mail address and use name
(setq mail-user-agent 'message-user-agent)
(setq user-mail-address "prashantrameshtak@gmail.com"
      user-full-name "Prashant Tak")
;; smtp config
(setq smtpmail-smtp-server "smtp.gmail.com"
      message-send-mail-function 'message-smtpmail-send-it)

;; report problems with the smtp server
(setq smtpmail-debug-info t)
;; add Cc and Bcc headers to the message buffer
(setq message-default-mail-headers "Cc: \nBcc: \n")
;; postponed message is put in the following draft directory
(setq message-auto-save-directory "~/.mail/gmail/draft")
(setq message-kill-buffer-on-exit t)
;; change the directory to store the sent mail
(setq message-directory "~/.mail/gmail/")
#+END_SRC

* EMMS
Although I'm not using emms on my current OS, these might prove useful if I decide to ditch ncmpcpp.

#+BEGIN_SRC emacs-lisp
;;(use-package emms
;;:ensure t
;;:config
;;(require 'emms-setup)
;;(require 'emms-player-mplayer)
;;(emms-all)
;;(setq emms-player-list '(
;;                         emms-player-mpg321
;;                         emms-player-ogg123
;;                         emms-player-mplayer
;;                         ))
;;(defun emms-player-mplayer-volume(amount)
;;  (process-send-string
;;   emms-player-simple-process-name
;;   (format "volume %d\n" amount)))
;;(setq emms-volume-change-function 'emms-player-mplayer-volume)
;;(setq emms-source-file-default-directory "D:/Music/")
;;(setq emms-playlist-buffer-name "*Music*")
;;(emms-add-directory-tree emms-source-file-default-directory)
;;)
#+END_SRC

* C++
Need to figure this stuff out (WIP)

#+BEGIN_SRC emacs-lisp
;;(after! cc-mode
;;  (set-company-backend! 'c-mode
;;    '(:separate company-irony-c-headers company-irony)))
;;Windows
;;(after! lsp-mode
;;  (set-lsp-priority! 'clangd 1))
;;
;;Linux
;;(after! lsp-mode
;;  (require 'dap-cpptools)
;;  (yas-global-mode)
;;  )
#+END_SRC
* Dictionary
Need to add the search from anywhere shortcut? DO I? Just verify later.

#+BEGIN_SRC emacs-lisp
(use-package! lexic
  :commands lexic-search lexic-list-dictionary
  :config
  (map! :map lexic-mode-map
        :n "q" #'lexic-return-from-lexic
        :nv "RET" #'lexic-search-word-at-point
        :n "a" #'outline-show-all
        :n "h" (cmd! (outline-hide-sublevels 3))
        :n "o" #'lexic-toggle-entry
        :n "n" #'lexic-next-entry
        :n "N" (cmd! (lexic-next-entry t))
        :n "p" #'lexic-previous-entry
        :n "P" (cmd! (lexic-previous-entry t))
        :n "C-p" #'lexic-search-history-backwards
        :n "C-n" #'lexic-search-history-forwards
        :n "/" (cmd! (call-interactively #'lexic-search))))

(defadvice! +lookup/dictionary-definition-lexic (identifier &optional arg)
  "Look up the definition of the word at point (or selection) using `lexic-search'."
  :override #'+lookup/dictionary-definition
  (interactive
   (list (or (doom-thing-at-point-or-region 'word)
             (read-string "Look up in dictionary: "))
         current-prefix-arg))
  (lexic-search identifier nil nil t))
#+END_SRC
* Openwith
This is still finnicky, I have to configure the various formats so that they work nicely with dired.

#+BEGIN_SRC emacs-lisp
(load! "~/.doom.d/openwith")
(require 'openwith)
(add-hook 'dired-mode-hook 'openwith-mode 1)

;;(load! "~/.emacs.d/elegant-emacs/sanity")
;;(load! "~/.emacs.d/elegant-emacs/elegance")
#+END_SRC
* Spotify

Spotify's app is too slow and clunky for my taste, let's attempt to use the player within emacs. (TODO: Figure out how to start spotify with a daemon or something)
#+BEGIN_SRC emacs-lisp
(setq counsel-spotify-client-id "d9d7e317a9b344a886d71643341cb796"
      counsel-spotify-client-secret "6e91aa96e0c1451ab8ad0da705983082"
      )
#+END_SRC

Also let's add some keybinds.

#+BEGIN_SRC emacs-lisp
(map! :n "SPC a t" #'counsel-spotify-toggle-play-pause
      :n "SPC a <" #'counsel-spotify-previous
      :n "SPC a >" #'counsel-spotify-next
      :n "SPC a s" #'counsel-spotify-search-track
      :n "SPC a p" #'counsel-spotify-search-playlist
      )
#+END_SRC

* El Secretario
This is a trial run for a package.

#+BEGIN_SRC emacs-lisp
(use-package! el-secretario-org
  :after (el-secretario))
(use-package! el-secretario-notmuch
  :after (el-secretario))

(use-package! el-secretario
  :config
  (defun my/dailyreview-secretary ()
    (list

     ;; First take care of email
     (el-secretario-notmuch-make-source "tag:unread")
     ;; Then Take care of inbox
     (el-secretario-org-make-source nil ("/mnt/Data/Documents/org/index.org"))

     ;; Check if any waiting items are done
    ;;(el-secretario-org-make-source (todo "WAITING") ("~/org/orgzly/Todo.org"))
     ;; Go through TODOs
    ;; (el-secretario-org-make-source (todo "TODO") ("~/org/orgzly/Todo.org"))
     )
    )
  ;; Create a function to start the review
  (defun el-secretario-daily-review ()
    (interactive)
    (el-secretario-start-session (my/dailyreview-secretary)))
  :commands (el-secretario-daily-review)
  )

#+END_SRC
